version: "3"
volumes:
  dera_rest_api_db_data:
services:
  dera_rest_api_db:
    image: "docker.io/postgres:alpine"
    hostname: "postgres_dera_rest_api"
    container_name: "postgres_dera_rest_api"
    restart: on-failure
    volumes:
      - "dera_rest_api_db_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=${DB_USER:-dera}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD:-password123}"
      - "POSTGRES_DB=${DB_NAME:-dera_db}"
  dera_rest_api:
    build:
      context: .
    image: "ghcr.io/dera-project/dera_rest_api:latest"
    hostname: "dera_rest_api"
    container_name: "dera_rest_api"
    restart: on-failure
    depends_on:
      - dera_rest_api_db
    ports:
      - "8080:8080"
