version: "3"
volumes:
  postgresql_repair_cafe_backend_data:
services:
  postgresql_repair_cafe_backend:
    image: "docker.io/postgres:alpine"
    hostname: "postgres_repair_cafe_backend"
    container_name: "postgres_repair_cafe_backend"
    restart: on-failure
    volumes:
      - "postgresql_repair_cafe_backend_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=${DB_USER:-repair_cafe_backend_user}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD:-password123}"
      - "POSTGRES_DB=${DB_NAME:-repair_cafe_backend_db}"
  repair_cafe_backend:
    build:
      context: .
    image: "ghcr.io/chineham-repair-cafe/repair_cafe_backend:latest"
    hostname: "repair_cafe_backend"
    container_name: "repair_cafe_backend"
    restart: on-failure
    depends_on:
      - postgresql_repair_cafe_backend
    ports:
      - "8080:8080"
