version: "3"
volumes:
  postgresql_dera_spring_app_data:
services:
  postgresql_dera_spring_app:
    image: "docker.io/postgres:alpine"
    hostname: "postgres_dera_spring_app"
    container_name: "postgres_dera_spring_app"
    restart: on-failure
    volumes:
      - "postgresql_dera_spring_app_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=${DB_USER:-dera_spring_app_user}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD:-password123}"
      - "POSTGRES_DB=${DB_NAME:-dera_spring_app_db}"
  dera_spring_app:
    build:
      context: .
    image: "ghcr.io/dera-project/dera_spring_app:latest"
    hostname: "dera_spring_app"
    container_name: "dera_spring_app"
    restart: on-failure
    depends_on:
      - postgresql_dera_spring_app
    ports:
      - "8080:8080"
