name: Fly.io Deployment Workflow

on:
  workflow_run:
    workflows: ["Container Image builder"]
    types: [completed]
  workflow_dispatch:
  push:

jobs:
  deploy-prod:
    name: Deploy to Fly.io
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install `flyctl`
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build and deploy to Fly.io
        run: flyctl deploy --local-only -c fly-prod.toml

  deploy-staging:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install `flyctl`
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build and deploy to Fly.io
        run: flyctl deploy --local-only -c ./fly-staging.toml
